### ISSUE TITLE
Question about method HL7Exception.populate

### ISSUE THREAD

**Issue by limsbeheer** [duaneedwards/nHapi#12]
We use method `HL7Exception.populate` to populate the ERR-segment of an ACK-message when an HL7Exception has been caught.
Every time we call this method `System.InvalidOperationException` ('The ConnectionString property has not been initialized.') is thrown since we do not use a database to provide a value to ERR-1-4-2.
Is it possible to catch this exception in method `HL7Exception.populate` for developers who do not (want to) use the database functionality? For now only a `LookupException` is caught.

**Comment by duaneedwards** [comment]
That makes sense to do, I don't suspect anyone will be shipping the database with nHapi so I'll change it to catch InvalidOperationExceptions as well shortly.
