### ISSUE TITLE
Version 2.1 is missing from LoadBaseVersions

### ISSUE THREAD

**Issue by taiji123** [duaneedwards/nHapi#13]
Failed processing messages with 2.1 version.  All the DLLs were in place, so wasn't a config issue.  The error text brought me to this line inside LoadBaseVersions method in NHapi.Base.PackageManager:

string[] versions = new string[] { "2.2", "2.3", "2.3.1", "2.4", "2.5" };

I added "2.1" to that array, and all started working.

Would hate to modify (and therefore having to maintain) your (original) code, so was wondering what were the reasons for pulling "2.1" from that list?  (I'm assuming it was there at some point in the past...?)

Thanks

**Comment by duaneedwards** [comment]
Looking at the svn logs, it looks like it's been this way from day one (back in 2006), which is long before I got involved with the project.

So I don't actually know why it was never put into that list to begin with.

I've added it back in and did a simple test to see that it parses as it should, it seems to be working alright.

I'll push this change up to nuget shortly.

**Comment by taiji123** [comment]
Awesome; thank you!
