### ISSUE TITLE
ORU_R01 v2.5.1 parsing issue

### ISSUE THREAD

**Issue by rajputs6** [duaneedwards/nHapi#15]
Hi Everyone, 
           I am trying to load ORU_R01 lab result but its causing issue and observations are not loading . 

We also generated OML_021 lab order with v 2.5.1 successfully 

 Only problem is ORU_R01 . 

 GetPATIENT_RESULT(0).ORDER_OBSERVATIONRepetitionsUsed is not going to set and also when debug the 

 GetPATIENT_RESULT(0) shows (_item prop) 2 structures one is ORU_R01_PATIENT and second ORU_R01_ORDER_OBSERVATION. But once we call 

 GetPATIENT_RESULT(0).GetAll("ORDER_OBSERVATION") return list with 0 items 

 ORU_R01_PATIENT is fine. 

 Please suggest 

 Thanks 
 Asghar

**Comment by bbunderson** [comment]
What version are you using? This issue was addressed around 2.4.0.7.

**Comment by rajputs6** [comment]
we are using a year old build we downloaded . i.e. 2.4.0.3 . do we need to update ? . which version should we use ? 

Thanks

**Comment by rajputs6** [comment]
Sorry correction.That was  2.4.0.1 we downloaded from codeplex site . do we need to update ? . which version should we use ? 

Thanks

**Comment by bbunderson** [comment]
The best option would be to use the latest Nuget package.

**Comment by duaneedwards** [comment]
bbunderson is right, I believe this is the issue that was resolved a little while ago in 2.4.0.6.

You can get the latest nHapi off of nuget using

```
Install-Package nHapi
```
Or just using the Package Manager screen in Visual Studio.

If this problem still occurs on latest, please provide a test harness for me to look into.

**Comment by rajputs6** [comment]
Hi bbunderson/duaneedwards , 
                                                     I updated with latest build bot no success. I have uploaded  test application for your reference . can you please check and suggest. Thanks in advance 


https://onedrive.live.com/redir?resid=8c649d61ddd7a893!244&authkey=!ALJgCXROUSlKNoQ&ithint=folder%2czip

**Comment by duaneedwards** [comment]
rajputs6, I've had a look at your project and the basic problem is message itself.

There are no escape characters between the segments (PID, ORC, OBR, OBX, SPM).

I can see you manually inserted an Environment.Newline character between the MSH and PID segments.  If you use the same approach of adding those Environment.Newline characters between all of the other segments (PID, ORC, OBR, OBX, SPM), the parser will split the segments correctly and your ObservationRepeitionsUsed will show 1 as you'd expect.

Hope this helps,

**Comment by rajputs6** [comment]
Thanks all for the help . it worked . Now after update to latest version I got  GetOBSERVATION(int rep) which was not available in old build we were using . Now I am able to parse message.
