### ISSUE TITLE
Planned support for newer specifications

### ISSUE THREAD

**Issue by Sikkesoft** [duaneedwards/nHapi#17]
Hi Duane,

Are there any plans to support HL 7 v2.6 and v2.7 specifications?
If so by what time?

**Comment by duaneedwards** [comment]
Not in the immediate future, as there are some issues with the code generator which produce different results than the current model libraries within nHapi.

These should be resolved before generating the newer HL7 specification parsers so that the project remains consistent in behaviour.

**Comment by juvasquezg** [comment]
Hi All,

I need support HL7 v3 in .Net, can you recommend me? is dificult? 

Thank you So Much.

**Comment by duaneedwards** [comment]
V3 is a totally different standard and is basically outside the scope of nHapi.

There are other open source solutions for the V3 standard such as http://hl7sdk.codeplex.com/ however it's GPL licensing may prove to be an issue depending on your method of usage.
