### ISSUE TITLE
No Support for nHapi for v2.7

### ISSUE THREAD

**Issue by AdamKalnas** [duaneedwards/nHapi#27]
Looking at the HL7 standards, I see that the latest version of the HL7 standards is v2.7, which was published in 2011.  It's :crying_cat_face: that nHapi doesn't support v2.7

**Comment by duaneedwards** [comment]
Now that I have access to a copy of the latest HL7 standards database I have generated an initial implementation of the v2.7 standard. (The databases were not cheap at all :-s)

There may well be issues with this implementation but at least now initial support is available.  The latest version of nHapi (version 2.5+) includes this implementation and is now available on nuget.
