### ISSUE TITLE
nHapi 2.4.0.8 and upwards break Custom Models discoverability

### ISSUE THREAD

**Issue by lniedzielski** [duaneedwards/nHapi#28]
nHapi generates GenericMessage instead of proper custom one. It used to work from versions 2.4.0.0-2.4.0.7 but 2.4.0.8 breaks it. 
It's pretty straightfoward to test with example "Invalid MSH-9 Example" from http://www.dib0.nl/code/478-nhapi-and-generic-messages-using-the-terser-or-custom-message-classes

**Comment by duaneedwards** [comment]
Thanks for reporting this issue, the original behaviour has now been resolved and a release with this fix is now up on nuget (v2.4.0.15)
