### ISSUE TITLE
Custom Model discoverability and HL7 versioning

### ISSUE THREAD

**Issue by lniedzielski** [duaneedwards/nHapi#29]
In order to point nHapi to custom models one needs to configure App.config to something like:

	<Hl7PackageCollection>
		<HL7Package name="MyNamspace.CustomModel." version="2.3"/>
	</Hl7PackageCollection>

The problem is I cannot set version attribute to anything above like 2.4 or 2.5. Otherwise Parser generates generic messages without resolving to custom classes.

**Comment by bushperi** [comment]
Hi, even i am facing this issue.
I know this issue has been closed long time back.
But any clue as to what resolved this issue?
