### ISSUE TITLE
V251 ADT_A01 Insurance Repetitions

### ISSUE THREAD

**Issue by rutzelt** [duaneedwards/nHapi#30]
Hello.  I recently started using version 2.5.1 of the nHapi model for a project I'm doing.  First of all, thanks to everyone for supporting this library.  It is extremely helpful.

I have to create an INSURANCE segment dynamically based on 1..n segments.  I had formerly used version 2.3.1 for this purpose.  Using that version, I was able to use GetInsurance(index) where it would automatically create the multiple INS segments.  With 2.5.1, I'm having trouble finding this functionality.  We are OK with one segment but not more.  We have also run the reverse scenario where an HL7 message with multiple IN1 and IN2 segments gets parsed into IN1, IN12, IN13, etc.  We are trying to programmatically create the same structure.  Is there an enhancement I can made to the 2.5.1 IGroup or is there a different way of achieving this functionality that I am not currently aware of?

Thank you.
-Tom

**Comment by duaneedwards** [comment]
This issue appears to be resolved now that the v251 models have been regenerated from the latest HL7 standards database.  I suspect this was an issue with the HL7 standards database that was used at the time that nHapi was previously generated (before I was involved with the project).

Here is the diff of the change that shows that the ADT_A01_INSURANCE has been changed to repeating:

![image](https://cloud.githubusercontent.com/assets/65170/16859615/a102e850-4a73-11e6-9e76-37c8b5d9dbe6.png)

Closing as I suspect this is no longer an issue.
