### ISSUE TITLE
V 2.5.1 ADT_A04 & ADT_A08 message types not found .

### ISSUE THREAD

**Issue by rajputs6** [duaneedwards/nHapi#32]
Hi , 
        I am trying to create AD_A04 & ADT_A08 but these message types are not available in v2.5.1 . Please suggest. I can see that these message types are available in 2.3.1 . I am using little bit older version of library 1.x 

Thanks in advance

**Comment by rutzelt** [comment]
The ADT^A08 event uses message structure ADT_A01.

**Comment by rajputs6** [comment]
Thanks it worked

Sent from Outlook




On Tue, Aug 4, 2015 at 8:51 AM -0700, "rutzelt" <notifications@github.com> wrote:
The ADT^A08 event uses message structure ADT_A01.

---

**Comment by menasheu** [comment]
But what about decoding an ADT-A04 message?

**Comment by uhlda** [comment]
Any answer on the previous question? How would we decode AO4's and A08's using the PipeParser - it returns a generic message type instead of the strongly typed A01.  The goal would be to get a strongly typed A01 in return if that's going to be the 'common' model.

**Comment by Eric-Cadwell** [comment]
Both ADT^A08 and ADT^A04 should be using the standard ADT_A01 structure. There should be a message mapping data file that would map the ADT_A08 type to the ADT_A01 structure. I don't see the EventMapping properties file in the 2.5.1 branch so I'm not sure if it is identifying the underlying structure.

**Comment by uhlda** [comment]
Unfortunately, I'm still very much a novice and have no idea how to use/setup a message map data file - is there any documentation out there anywhere that describes this process? Considering that 
'native' A04/A08 support is lacking in both v2.4 and v2.5 this should be a pretty common need...

**Comment by duaneedwards** [comment]
@uhlda The latest version of nHapi now up on nuget (2.4.0.14) should resolve this issue (specifically for version 2.5.1).  The unit test 'TestADTA04IsMappedAsA01' in the 'PipeParsingFixture251' class show how an A04 will ultimately be parsed into the A01 message structure.

If it doesn't work as you'd expect send through more details / provide a unit test showing the problem and I'll try and have a look into the issue further.

**Comment by uhlda** [comment]
Got the latest version from Nuget and everything appears to be mapping correctly (i.e., A04,A08 to A01) - thank you very much!
