### ISSUE TITLE
HL7 2.5.1 ORU_R01 RelevantClinicalInformation OBR-13  ST Type not compatible 

### ISSUE THREAD

**Issue by rajputs6** [duaneedwards/nHapi#33]
Hi , 
       I found that the RelevantClinicalInformation OBR-13 is of type ST but as per HL7 standard it should be CE .  http://hl7v2-lab-testing.nist.gov/mu-lab/. 

To make it workable I have made it to CE and it worked for me . I am using version Nhapi 1.9. If it is fixed in latest release then please reply.

Thanks

**Comment by duaneedwards** [comment]
I'm not sure about the above link that you have posted, however referencing the HL7 standard for v2.5.1 document shows that OBR-13 is in fact a ST datatype:

![image](https://cloud.githubusercontent.com/assets/65170/16859524/e1d7593e-4a72-11e6-8240-f8cfabe4bc9a.png)

Closing as I don't suspect this is actually an issue.
