### ISSUE TITLE
NHapi.Model.V251.Group.OUL_R22_ORDER without RESULT

### ISSUE THREAD

**Issue by nono37** [duaneedwards/nHapi#37]
The object NHapi.Model.V251.Group.OUL_R22_ORDER have a Property "OBXTCDSIDNTE".
This property should not exist !
It seems it's a part of group "RESULT".

**Comment by rpunselie** [comment]
Agreed. 
As the OBX in OBXTCDSIDNTE is non repeatable, only the first OBX can be retrieved. HL7 specs allow multiple results per order (and thus multiple OBX segments).

In my opinion, the correct structure would be:

...
order begin
  OBR
  NTE
  ORC
  timing_qty begin
    TQ1
  timing_qty end
  **_result begin (0..n)
    OBX (1..1)
    TCD (0..1)
    INV (0..n)
    NTE (0..n)
  result end_**
order end
...

**Comment by duaneedwards** [comment]
This issue appears to be resolved now that the v251 models have been regenerated from the latest HL7 standards database.  I suspect this was an issue with the HL7 standards database that was used at the time that nHapi was previously generated (before I was involved with the project).
