### ISSUE TITLE
TSComponentOne GetAsDate does not handle offset from UTC/GMT

### ISSUE THREAD

**Issue by Eric-Cadwell** [duaneedwards/nHapi#38]
Some messages we process have the date/time of message in MSH formatted with the time zone offset from UTC/GMT. However there isn't a formatting string that matches enough for the ParseExact to work. We can provide a format string of yyyyMMddHHmmsszzz to parse the time zone offset properly.

**Comment by duaneedwards** [comment]
The latest release of nHapi (version 2.5.0.3) includes the changes from pull the pull request for this issue and is up on nuget.  Just be wary there may be some breaking changes due to the structure being regenerated based off a more correct standards database as of nHapi version 2.5+.
