### ISSUE TITLE
Whitespace after version number causes an issue

### ISSUE THREAD

**Issue by Eric-Cadwell** [duaneedwards/nHapi#39]
If there is white space after the version number it can cause the parser to be unable to find the proper message class from the class factory. When checking versions in IsValidVersion() method strips trailing/preceding white space using string.Trim() but it doesn't do this in other locations, so the dictionary look up ends up using "2.3 " instead of "2.3" and fails to find an entry for the key. There's also a package version check at some other point that will also fail due to "2.3 " not being equal to "2.3". Primarily if trimming white space is done in one location it probably should be done elsewhere, especially since the version is used as keys in dictionary look ups.

**Comment by duaneedwards** [comment]
The latest release of nHapi (version 2.5.0.3) includes the changes from pull the pull request for this issue and is up on nuget.  Just be wary there may be some breaking changes due to the structure being regenerated based off a more correct standards database as of nHapi version 2.5+.
