### ISSUE TITLE
Unexpected Segments cause later parsing issues

### ISSUE THREAD

**Issue by Eric-Cadwell** [duaneedwards/nHapi#40]
When processing a message with an unexpected segment it throws off the remaining segments from being processed correctly for the message. This seems to be due to the iterators getting to the end of a group and never walking back up to where the iterator was last. Upon the next segment being processed it starts from that point and continues forward, potentially being past the point where the matching segment was in the iterator.

Example:
MSH|^~\&|EMR|Sending|Dest|Receiving|20150216152626||ORM^O01|1|P|2.3.1|||AL||||||
EVN|O01|20150216152626
PID||1|1||q^q|||F||||||||||||

In the above message getting Patient's name results in a null value.

**Comment by Eric-Cadwell** [comment]
I've had to make an additional changes due to how repetitions for segments were relying on beginning from that point in the message navigator.

**Comment by duaneedwards** [comment]
The latest release of nHapi (version 2.5.0.3) includes the changes from pull the pull request for this issue and is up on nuget.  Just be wary there may be some breaking changes due to the structure being regenerated based off a more correct standards database as of nHapi version 2.5+.
