### ISSUE TITLE
How to validate a 2.3 standard message ?

### ISSUE THREAD

**Issue by ohadinho** [duaneedwards/nHapi#42]
Hi,
There is no documentation at all of how should a user validate a message with this project.
Can someone assist ?

**Comment by duaneedwards** [comment]
Closing as this is a duplicate of #46 Missing conformance profile validation

**Comment by milkshakeuk** [comment]
@ohadinho there are some useful tutorials on validating with nhapi [here](https://saravanansubramanian.com/hl7tutorials/#hl7-programming-tutorials-using-nhapi-and-net).
