### ISSUE TITLE
Message escaping isn't functioning properly on all UNC strings

### ISSUE THREAD

**Issue by Eric-Cadwell** [duaneedwards/nHapi#44]
If you have a UNC string that contains a character that matches a special character (X,Z,C,M,H,N,S) immediately after a '\' character the escape class treats this as you intended to have the special escaped special character there even if the third character in the sequence doesn't match. For example one special character encoding should be \S\ but if you have \\Server\Share those shouldn't be flagged as special character because the next slash is not immediately following.

**Comment by thenulldeveloper** [comment]
I also just ran across this situation as well. I set a field to \\DEV\Share\report_v2\output.pdf and it is encoded as \E\\E\DEV\Share\report_v2\E\output.pdf

Note that the \ between DEV and Share and the \ between Share and report are not encoded.

**Comment by Eric-Cadwell** [comment]
I have made changes to the escaping function in my fork of the project [https://github.com/Eric-Cadwell/nHapi](https://github.com/Eric-Cadwell/nHapi). So that may the easiest way to get the fixes.

**Comment by thenulldeveloper** [comment]
Thank you Eric! This is most kind of you. I will do so this evening!

All the best,

Kevin

On Wed, Apr 6, 2016 at 12:12 PM, Eric Steinbrenner <notifications@github.com

**Comment by duaneedwards** [comment]
The latest release of nHapi (version 2.5.0.3) includes the changes from pull the pull request for this issue and is up on nuget.  Just be wary there may be some breaking changes due to the structure being regenerated based off a more correct standards database as of nHapi version 2.5+.
