### ISSUE TITLE
Requesting code example for message types that are not provided directly.  

### ISSUE THREAD

**Issue by TPucke** [duaneedwards/nHapi#47]
Recognizing that some message classes are intended for use to implement other messages (e.g. A01 supports A04 and A08), can you please provide a wiki page to illustrate the decoding of an A04 or A08 message.  When I parse a message of either type I get an instance of class NHapi.Base.Model.GenericMessage+V25 and this seems unlikely that my application should have to provide special handling to decode a standard message.  Have I missed something?

**Comment by sychare** [comment]
If you're trying to parse an ADT^A04 or A08) you will want to be sent ADT_A01 in MSH-9-3 (e.g. MSH-9 = ADT^A08^ADT_A01). The HL7 spec hints as such, but nobody implements HL7 by the spec, obviously. ;)

To deal with 'bad' senders we opted to write a pre-nHapi interception that re-writes incoming ADT^A04/8s without the message structure segment to add the segment prior to processing.

**Comment by duaneedwards** [comment]
This looks like this may have been related to an issue where the Event to Structure map for v2.5.1 messages was not present.  This has been recently fixed and is available up on nuget now.

In addition I've created a small wiki entry below giving an example of how the event to code structure map should be working:

https://github.com/duaneedwards/nHapi/wiki/Decoding-a-message#event-map-to-code-structure-mappings
