### ISSUE TITLE
Small bug in milliseconds parsing CommonTM.cs

### ISSUE THREAD

**Issue by dib0** [duaneedwards/nHapi#48]
When parsing a date/time including milliseconds (for example "19460408000000.000") CommonTM throws an exception on line 236:
float fract = Single.Parse(timeVal.Substring(6));
I can't figure out why exactly, since my OS is set to "en-US", but somehow the parsing of ".000" fails. This is solved by adding a InvariantCulture:
float fract = Single.Parse(timeVal.Substring(6), CultureInfo.InvariantCulture);

**Comment by Eric-Cadwell** [comment]
Was the exception: "Input string was not in a correct format."

It is possible that the format rules can be customized even when the region is still set to en-US.  You can always check what these are by going into Region and Language and clicking "Additional settings..." to see any customized separators. InvariantCulture is designed to not use any custom format rules.

This fix may still be good if HL7 expects the formatting to never use local formatted time strings, but this would break if there is ever a local formatted time string.

**Comment by dib0** [comment]
Yes, that was the exception.

You are right. In this case the handling of the date/time by nHapi makes sure the formatting can't handle other formats than the standard one.

This really specific parsing is done on the last part of the string, the milliseconds. The problem is that the substring of 4 characters is taken, starting with the ".". This is parsed to a number/Single. The case here is that not all languages/cultures accept a string starting with a "." to be a valid number.

So .000 is always the format (checked before that) and mandatory. This will not parse correctly in some culture settings. The code therefore assumes that the culture is set to "en-US" or another one that accepts a string like this as a number.

So, the string is always formatted like this, there is no localization here. I don't think this will break at all, just prevent breaking in some environments.

**Comment by duaneedwards** [comment]
The latest release of nHapi (version 2.5.0.4) includes the changes from pull the pull request for this issue and is up on nuget.  Just be wary there may be some breaking changes due to the structure being regenerated based off a more correct standards database as of nHapi version 2.5+.
