### ISSUE TITLE
can't process message of version 2.3.0 - version not recognized 

### ISSUE THREAD

**Issue by bhupinder7** [duaneedwards/nHapi#53]
Hi , I'm using this .Net library in one of my project to parse hl7 messages . But, when i try to parse i get this error. I checked the hl7 message that i send, it has the version 2.3.0. I believe the version is not matching with the complied package names. The package name is 2.3 but the version in my message is 2.3.0. Does anybody can tell how can i solve this issue ?

Thanks,
Bhupinder

**Comment by duaneedwards** [comment]
I wouldn't expect that 2.3.0 would parse as correctly as there isn't a
2.3.0 HL7 message standard.

Try changing the message to 2.3 to see if it parses correctly.

nHapi isn't very forgiving of messages that don't conform to the exact HL7
specifications

**Comment by bhupinder7** [comment]
Thanks !
