### ISSUE TITLE
V2.5 not able to parse Gt1 segments

### ISSUE THREAD

**Issue by crudler** [duaneedwards/nHapi#54]
For any DFT message (e.g.)

> MSH|^~\&|CWM|FUJI|UNKNOWN|UNKNOWN|20160711080000||DFT^P03|976503|P|2.5|
> EVN|P03|20160711080000
> PID||12345^^^RIS|||Test^Patient||197206200000|F|||7 BOB AVEVENUE^^WENDYWOOD^^4309|||m0825123759|3|S|||23377|||||||||||N
> PV1||I||||||999^Ref Doctor^||||||||N||A|160998675|||||||||||||||||||||||||20160701130000
> GT1|1||EVERYMAN^ADAM^A||2222 HOME STREET^^ISHPEMING^MI^49849^""^|444-33 3333|555-555-2004||||SEL^SELF|444-33 3333||||AUTO CLINIC|2222 HOME STREET^^ISHPEMING^MI^49849^""|555-555-2004|
> OBR|1||2015021000043|20310^CT of the soft tissues of the neck, with contrast^CT^4^CT Scan Machine|0|201502101124|201502101124|||||||||^ISMAIL^KHALEEL||||||||IMIL
> FT1|1|E292252||201502101124||CG|00279519|F||1|||IMIL|PRIVATE^||||A1|||^ISMAIL^KHALEEL^^^||2015021000043^IMIL||20310^CT of the soft tissues of the neck, with contrast^CT^4^CT Scan Machine|CT
> PR1|1|AQ|20310^CT of the soft tissues of the neck, with contrast^CT^4^CT Scan Machine||201502101124|D||||||||||CT|

```
            PipeParser parser = new PipeParser();
            IMessage m = parser.Parse(msg);            
            DFT_P03 dft = m as DFT_P03;
```

nHapi is unable to parse the GT1 segment, and instead creates a new one
`         GT1 gt1 = dft.GetGT1(0);`
``with nulls instead of parsed values

I "think" this is an issue.

Thank you for maintaining a really excellent project

**Comment by akhansari** [comment]
I have the same issue with PV1 when a custom segment (like ZFP) comes juste before the PV1.

**Comment by crudler** [comment]
Also is the DFT message?
mine doesnt even have any Z segments. Weirdly my PV1 parses correctly

**Comment by akhansari** [comment]
Nop, it's a ADT_A01 message but with the same bug.
PV1 is created twice and the parsed data is filled in the seconde one. In the getter the first one is returned which is null...

**Comment by crudler** [comment]
Some very clever person on StackOverflow solved this for me. looks like a bug. but its not. **Order matters**. 
HL7 spec puts the GT1 below procedures and transactions
[https://corepointhealth.com/resource-center/hl7-resources/hl7-dft-detail-financial-transaction](url)
and even the dft comments lists the order
When i followed them correctlly, it solved the problem.
Have you tried moving your Z segment to the bottom? In truth I have only ever seen it right at the bottom so it might be related

**Comment by Eric-Cadwell** [comment]
This could also be a case of issue #40, where unexpected segments caused the parser to advanced forward and never revisit the skipped over segments. It would leave a blank segment there and then treat the skipped segments as unexpected and add them into the bucket that those fall into.

**Comment by akhansari** [comment]
I'm not sure but I think order is important only for the elements in a group!
So I think it's still a bug...
