### ISSUE TITLE
Description Fields

### ISSUE THREAD

**Issue by THEStephenStanton** [duaneedwards/nHapi#8]
I noticed that when trying to get the descriptions of each segment that the Description field is always null and the only way to get it is to use the method .GetFieldDescription(num).  For instance I am using an ORM_O01 and to access PID.7 orm.PATIENT.PID.DateTimeOfBirth.Description is always null yet orm.PATIENT.PID.GetFieldDescription(7) gives me the value I am looking for.

**Comment by THEStephenStanton** [comment]
Solved my own issue, I see how you structured it.

**Comment by duaneedwards** [comment]
I'm curious, which way did you end up using to access the data you were after?

**Comment by THEStephenStanton** [comment]
Basically I parsed each segment in the message, then casted each segment as an AbstractSegment then from there I used the NumFields() for a for loop so that I could access each field and field description by its index using GetFieldDescription() and GetFieldValue().  It was rather easy for the descriptions, the values were tricky though.  I had to use recursion and check the types to get some of values from the segments, also had to do it so that I could loop through every segment and every field.  Hope that made sense.

**Comment by duaneedwards** [comment]
Yes that made perfect sense, it helped me to see what you are trying to achieve.

I had a look into this and it wasn't too difficult to wire up the parser to populate the description fields, so now you will be able to use as you originally attempted to:

```
// Now returns "Date/Time of Birth":
var  description = orm.PATIENT.PID.DateTimeOfBirth.Description;
```

I'm going to package this into version 2.4.0.7 and push it up to nuget.org shortly if you'd like to have a look.

**Comment by THEStephenStanton** [comment]
Thanks! Works perfect.
