### ISSUE TITLE
DataTypeException.FieldPosition incorrect for MSH segment

### ISSUE THREAD

**Issue by limsbeheer** [duaneedwards/nHapi#9]
When catching a DataTypeException the FieldPosition property is incorrect for the MSH segment. For other segments it represents the correct field position number.

E.g. when MSH-7 (Date/Time of message) contains value '20151301' DataTypeException.FieldPosition holds number 6. Expected is 7.
For PID-7 (Date/time of birth) the number is indeed 7.

I think it's because MSH-1 (Field separator) is not counted in when parsing this segment.

**Comment by duaneedwards** [comment]
You're correct on this one as well, the problem was basically that for the segments with an offsetted field position (MSH / FHS / BHS), the offset wasn't being included as part of the field position when the caught exception was rethrown.

Fix to follow shortly.
